[WIP] Add popup with sensors details
CodeForAfrica/sensors.AFRICA-AQ-map pull request #12
Opened 2019-04-24 12:38 UTC by nerdlet

## Description
Fixes #165414013

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-04-29 12:00 UTC, karimkawambwa requested changes
Looks great 👍

2019-04-29 12:00 UTC, karimkawambwa commented on src/cell-info.vue
> +	h3 Active sensors:  {{cell.length}}
They are not necessarily active
Its the number of sensors clumped together in that map pinpoint

2019-04-29 12:00 UTC, karimkawambwa commented on src/feinstaub-api.js
> +          let date = Date(value.last_date_pushed);
This is now `last_data_received_at`

2019-04-30 09:27 UTC, nerdlet commented on src/cell-info.vue
> +	h3 Active sensors:  {{cell.length}}
@karimkawambwa Working on it

2019-04-30 12:13 UTC, karimkawambwa approved these changes
LGTM

2019-04-30 12:14 UTC, karimkawambwa commented
When ready to merge, remember to use production: `https://api.sensors.africa`

2019-05-02 06:59 UTC, kilemensi requested changes
Good stuff @nerdlet :+1: 

No need for `momentjs` though **if** all you're using it for is date format: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString is good enough.

2019-05-03 07:46 UTC, nerdlet commented
@kilemensi @karimkawambwa Sensor ids are displaying now

2019-05-07 11:48 UTC, karimkawambwa commented
Should we merge this and release ?

2019-05-08 05:32 UTC, merged