[Sensors.AFRICA] Remove None PM sensors
CodeForAfrica/sensors.AFRICA-AQ-map pull request #14
Opened 2019-05-23 12:00 UTC by nerdlet

## Description
Remove readings of `undefined` id's variables for` P1 ` and ` P2 ` nodes. Nodes that have only ` humidity` and ` temperature `nodes

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/58250841-f57b1380-7d6a-11e9-90b4-1ef1efe5395e.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-05-23 14:28 UTC, karimkawambwa requested changes

2019-05-23 14:28 UTC, karimkawambwa commented on src/feinstaub-api.js
> +          console.log(id());
☝️

2019-05-24 08:44 UTC, nerdlet commented on src/feinstaub-api.js
> +          console.log(id());
Done

2019-05-24 12:39 UTC, karimkawambwa approved these changes

2019-05-27 13:10 UTC, merged